INSERT INTO AUTOR (ID, NOME) VALUES
  (1, 'Gupta'),
  (2, 'Vu'),
  (3, 'America');

INSERT INTO LIVRO (ID, NOME, QUANTIDADEPAGINAS, AUTOR_ID) VALUES
  (1, 'A VOLTA DOS QUE NÃO FORAM',200, 1),
  (2, 'POEIRA EM ALTO MAR',300, 2),
  (3, 'O CORONA VIRUS',400, 3);

INSERT INTO PERMISSAO (ID, PERMISSAO) VALUES
  (1, 'ROLE_VISITANTE'),
  (2, 'ROLE_ADMIN'),
  (3, 'ROLE_MANTEDOR');

INSERT INTO USUARIO (ID, USUARIO, SENHA) VALUES
  (1, 'admin', '$2a$10$8DuqrRBz71ubdVQnQ5NbtOKteoGRXtwqKC4DDEWG5EZnAYRpdrIqm'),
  (2, 'teste', '$2a$10$PNDsgGFqsyGjA2hF0XcsR.XJDc1Hxz78Sudy6kVZPt8sUC9iMXONi');

INSERT INTO PERMISSAO_USUARIO (USUARIO_ID, PERMISSAO_ID) VALUES
  (1, 1),
  (1, 2),
  (1, 3),
  (2, 2);