INSERT INTO AUTOR (ID, NOME) VALUES
  (1, 'Gupta'),
  (2, 'Vu'),
  (3, 'America');

INSERT INTO LIVRO (ID, NOME, QUANTIDADEPAGINAS, AUTOR_ID) VALUES
  (1, 'A VOLTA DOS QUE NÃO FORAM',200, 1),
  (2, 'POEIRA EM ALTO MAR',300, 2),
  (3, 'O CORONA VIRUS',400, 3);

INSERT INTO PERMISSAO (ID, PERMISSAO, DESCRICAO) VALUES
  (1, 'ROLE_VISUALIZAR', 'Visualizar dados'),
  (2, 'ROLE_GERENCIA_USUARIOS', 'Gerenciar usuários'),
  (3, 'ROLE_ATUALIZAR_DADOS', 'Atualizar dados');

INSERT INTO USUARIO (ID, USUARIO, SENHA) VALUES
  (1, 'administrador', '$2a$10$H9/5tQjUOIl7rFqITsMY3.x59WfutrO2NB0lLFGPjNUFJgWqvmKMa'),
  (2, 'mantedor', '$2a$10$H9/5tQjUOIl7rFqITsMY3.x59WfutrO2NB0lLFGPjNUFJgWqvmKMa'),
  (3, 'visitante', '$2a$10$H9/5tQjUOIl7rFqITsMY3.x59WfutrO2NB0lLFGPjNUFJgWqvmKMa');

INSERT INTO PERMISSAO_USUARIO (USUARIO_ID, PERMISSAO_ID) VALUES
  (1, 1),
  (1, 2),
  (1, 3),
  (2, 1),
  (2, 3),
  (3, 1);
